M48
; DRILL file {KiCad 9.0.6} date 2026-03-21T14:22:37-0300
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-21T14:22:37-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X18.0Y-30.0
X40.0Y-18.0
X61.0Y-68.0
X83.0Y-16.0
M30
